apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    name: harbor
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv
  labels:
    app: harbor-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /media/ross/hp/virtualbox/nfs/harbor
    server: 172.16.11.84
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: harbor-pv

